/**
 * Screenshot freshness guard — shared between `repoos check` and
 * `scripts/capture-screenshots.mjs`.
 *
 * The committed PNGs under `screenshots/` are generated by the capture script
 * against a controlled fixture repo. This module defines what "fresh" means:
 * a sha256 over the UI source tree, the fixture repo, the capture script, AND
 * the committed PNGs themselves, compared against the marker the generator
 * writes to `screenshots/.ui-hash`. Any drift fails the `repoos check` gate so
 * the screenshots cannot silently rot.
 */
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

export const SHOTS_DIR = "screenshots";
export const HASH_FILE = join(SHOTS_DIR, ".ui-hash");
export const SCREENSHOT_NAMES = [
  "dashboard.png",
  "work-board.png",
  "task-drawer.png",
  "docs-context.png",
  "settings.png",
] as const;

/** Relative paths (sorted) that feed the freshness hash. */
function uiSources(root: string): string[] {
  const dirs = ["src/ui-app", "scripts/screenshot-fixtures"];
  const extraFiles = [
    "scripts/capture-screenshots.mjs",
    ...SCREENSHOT_NAMES.map((n) => join(SHOTS_DIR, n)),
  ];
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      const p = join(dir, e.name);
      if (e.isDirectory()) {
        if (e.name === "node_modules" || e.name === "dist") continue;
        walk(p);
      } else {
        out.push(p);
      }
    }
  };
  for (const d of dirs) {
    if (existsSync(join(root, d))) walk(join(root, d));
  }
  for (const f of extraFiles) {
    if (existsSync(join(root, f))) out.push(join(root, f));
  }
  return out.sort();
}

/** Hash of everything that determines the committed screenshots. */
export function screenshotsHash(root: string): string | null {
  if (!existsSync(join(root, "src/ui-app"))) return null;
  const hash = createHash("sha256");
  for (const f of uiSources(root)) {
    if (!statSync(f).isFile()) continue;
    hash.update(f.slice(root.length + 1));
    hash.update("\u0000");
    hash.update(readFileSync(f));
  }
  return hash.digest("hex");
}

/** True when committed screenshots do not match the current UI source. */
export function screenshotsStale(root: string): boolean {
  const marker = join(root, HASH_FILE);
  if (!existsSync(marker)) return true;
  const recorded = readFileSync(marker, "utf8").trim();
  const current = screenshotsHash(root);
  return current === null || recorded !== current;
}
