/**
 * Machine-level tunnel app registry.
 *
 * `cloudflared` on a machine runs as ONE system service reading ONE ingress
 * config — but each RepoOS repo checkout only knows about its own
 * `repoos.toml [tunnel.apps.*]`. Without a shared machine view, the second
 * repo to `repoos tunnel install` clobbers the first repo's ingress routes.
 *
 * This registry (`~/.config/repoos/tunnel-apps.toml` by default) is the
 * union of every repo's published apps on this box, keyed by app name, each
 * entry tagged with the repo checkout (`ownerRoot`) that contributed it.
 * `repoos.toml [tunnel.apps.*]` in each repo stays the per-repo, git-tracked
 * source of truth for that repo's own apps — this file is a derived,
 * machine-local cache that `repoos tunnel install`/`start` render the actual
 * `cloudflared` ingress from, so bringing up the service from ANY repo on the
 * machine serves every app published by any repo.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { parseToml, tomlQuote, type TunnelApp, type TunnelConfig } from "./tunnel.js";

/** A registry entry: a published app plus which repo checkout owns it. */
export interface RegistryApp extends TunnelApp {
  /** Absolute path to the repo checkout that created this app. */
  ownerRoot: string;
}

/** The machine-level registry: one shared tunnel identity + every repo's apps. */
export interface TunnelRegistry {
  tunnelId: string;
  tunnelName: string;
  domain: string;
  apps: Record<string, RegistryApp>;
}

export function emptyRegistry(): TunnelRegistry {
  return { tunnelId: "", tunnelName: "", domain: "", apps: {} };
}

/** Default location — one registry per machine, outside any repo. */
export function registryPath(): string {
  return join(homedir(), ".config", "repoos", "tunnel-apps.toml");
}

export function parseRegistry(text: string): TunnelRegistry {
  const root = parseToml(text);
  const reg = emptyRegistry();
  if (typeof root.tunnel_id === "string") reg.tunnelId = root.tunnel_id;
  if (typeof root.tunnel_name === "string") reg.tunnelName = root.tunnel_name;
  if (typeof root.domain === "string") reg.domain = root.domain;
  const rawApps = (root.apps ?? {}) as Record<string, Record<string, unknown>>;
  for (const [name, a] of Object.entries(rawApps)) {
    if (typeof a !== "object" || a === null) continue;
    reg.apps[name] = {
      hostname: String(a.hostname ?? ""),
      service: String(a.service ?? ""),
      access: Array.isArray(a.access) ? (a.access as unknown[]).map(String) : [],
      ...(a.noAccess === true ? { noAccess: true } : {}),
      ownerRoot: String(a.ownerRoot ?? ""),
    };
  }
  return reg;
}

export function serializeRegistry(reg: TunnelRegistry): string {
  const lines: string[] = [];
  lines.push(
    "# Generated by repoos tunnel — machine-level registry of every repo's published apps on this box.",
  );
  lines.push("# Do not hand-edit; see docs/tunnel-registry.md.");
  if (reg.tunnelId) lines.push(`tunnel_id = ${tomlQuote(reg.tunnelId)}`);
  if (reg.tunnelName) lines.push(`tunnel_name = ${tomlQuote(reg.tunnelName)}`);
  if (reg.domain) lines.push(`domain = ${tomlQuote(reg.domain)}`);
  for (const name of Object.keys(reg.apps).sort()) {
    const app = reg.apps[name];
    lines.push("");
    lines.push(`[apps.${name}]`);
    lines.push(`hostname = ${tomlQuote(app.hostname)}`);
    lines.push(`service = ${tomlQuote(app.service)}`);
    lines.push(`access = [${app.access.map(tomlQuote).join(", ")}]`);
    if (app.noAccess) lines.push(`noAccess = true`);
    lines.push(`ownerRoot = ${tomlQuote(app.ownerRoot)}`);
  }
  return lines.join("\n") + "\n";
}

/** Read the machine registry. Missing file reads as an empty registry. */
export function readRegistry(path: string = registryPath()): TunnelRegistry {
  const text = existsSync(path) ? readFileSync(path, "utf8") : "";
  return parseRegistry(text);
}

/** Persist the machine registry (0600 — same treatment as the derived ingress config). */
export function writeRegistry(reg: TunnelRegistry, path: string = registryPath()): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, serializeRegistry(reg), { encoding: "utf8", mode: 0o600 });
}

/**
 * Reconcile a repo's tunnel identity against the registry's. A machine runs
 * ONE Cloudflare Tunnel, so if the registry already has an identity and this
 * repo's disagrees, refuse rather than silently picking one — returns an
 * error message. When the registry has no identity yet, adopts the repo's
 * (mutates `reg` in place). No-ops when the repo itself isn't set up yet.
 */
export function reconcileIdentity(reg: TunnelRegistry, tunnel: TunnelConfig): string | null {
  if (!tunnel.tunnelId) return null;
  if (!reg.tunnelId) {
    reg.tunnelId = tunnel.tunnelId;
    reg.tunnelName = tunnel.name;
    if (!reg.domain) reg.domain = tunnel.domain;
    return null;
  }
  if (reg.tunnelId !== tunnel.tunnelId) {
    return (
      `This repo's tunnel (${tunnel.name || "unnamed"}, ${tunnel.tunnelId}) does not match ` +
      `the machine's registered tunnel (${reg.tunnelName || "unnamed"}, ${reg.tunnelId}). ` +
      `A machine runs ONE Cloudflare Tunnel — run \`repoos tunnel setup\` here to join the ` +
      `existing tunnel, or resolve the conflict by hand in ${registryPath()}.`
    );
  }
  return null;
}

/** Add or replace a registry entry, tagging it with its owning repo. */
export function upsertApp(
  reg: TunnelRegistry,
  name: string,
  app: TunnelApp,
  ownerRoot: string,
): void {
  reg.apps[name] = { ...app, ownerRoot };
}

/** Remove a registry entry (no-ops when absent). */
export function removeApp(reg: TunnelRegistry, name: string): void {
  delete reg.apps[name];
}

/** Strip `ownerRoot` back to plain `TunnelApp`s — the shape `renderCloudflaredConfig` expects. */
export function unionApps(reg: TunnelRegistry): Record<string, TunnelApp> {
  const out: Record<string, TunnelApp> = {};
  for (const [name, app] of Object.entries(reg.apps)) {
    out[name] = {
      hostname: app.hostname,
      service: app.service,
      access: app.access,
      ...(app.noAccess ? { noAccess: true } : {}),
    };
  }
  return out;
}

/**
 * Migration / self-healing seed: for every app in this repo's own
 * `repoos.toml`, add it to the registry under this repo's ownership UNLESS
 * the registry already has an entry with that name (from this repo or any
 * other — an existing entry is never overwritten here). Mutates `reg` in
 * place and returns the names that were newly seeded.
 *
 * Deliberately per-app rather than gated on "registry is totally empty":
 * on a machine with multiple PRE-EXISTING repos (each already publishing
 * its own apps before this registry existed), each repo seeds its own apps
 * into the registry the first time IT runs `create`/`install`/`start`,
 * regardless of whether another repo got there first and seeded its own —
 * that's exactly the scenario (celleris + dev on one tunnel) this registry
 * exists to fix. For the common single-repo case this still behaves like a
 * one-time full migration, since every app is missing on the first run and
 * none are ever touched again afterward.
 */
export function migrateFromRepo(reg: TunnelRegistry, tunnel: TunnelConfig, root: string): string[] {
  const seeded: string[] = [];
  for (const [name, app] of Object.entries(tunnel.apps)) {
    if (reg.apps[name]) continue;
    reg.apps[name] = { ...app, ownerRoot: root };
    seeded.push(name);
  }
  return seeded;
}

/** A registry entry annotated with whether its owning repo checkout still exists on disk. */
export interface RegistryAppHealth {
  name: string;
  app: RegistryApp;
  /** `ownerRoot` no longer exists on disk — the repo that published this app is gone. */
  stale: boolean;
}

/** Every registry app, sorted by name, annotated with staleness. */
export function annotateStale(reg: TunnelRegistry): RegistryAppHealth[] {
  return Object.entries(reg.apps)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, app]) => ({
      name,
      app,
      stale: !!app.ownerRoot && !existsSync(app.ownerRoot),
    }));
}
