/**
 * Machine-level tunnel app registry.
 *
 * `cloudflared` on a machine runs as ONE system service reading ONE ingress
 * config — but each RepoOS repo checkout only knows about its own
 * `repoos.toml [tunnel.apps.*]`. Without a shared machine view, the second
 * repo to `repoos tunnel install` clobbers the first repo's ingress routes.
 *
 * This registry (`~/.config/repoos/tunnel-apps.toml` by default) is the
 * union of every repo's published apps on this box, keyed by app name, each
 * entry tagged with the repo checkout (`ownerRoot`) that contributed it.
 * `repoos.toml [tunnel.apps.*]` in each repo stays the per-repo, git-tracked
 * source of truth for that repo's own apps — this file is a derived,
 * machine-local cache that `repoos tunnel install`/`start` render the actual
 * `cloudflared` ingress from, so bringing up the service from ANY repo on the
 * machine serves every app published by any repo.
 */
import {
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { parseToml, tomlQuote, type TunnelApp, type TunnelConfig } from "./tunnel.js";

/** A registry entry: a published app plus which repo checkout owns it. */
export interface RegistryApp extends TunnelApp {
  /** Absolute path to the repo checkout that created this app. */
  ownerRoot: string;
}

/** The machine-level registry: one shared tunnel identity + every repo's apps. */
export interface TunnelRegistry {
  tunnelId: string;
  tunnelName: string;
  domain: string;
  apps: Record<string, RegistryApp>;
}

export function emptyRegistry(): TunnelRegistry {
  return { tunnelId: "", tunnelName: "", domain: "", apps: {} };
}

/** Default location — one registry per machine, outside any repo. */
export function registryPath(): string {
  return join(homedir(), ".config", "repoos", "tunnel-apps.toml");
}

export function parseRegistry(text: string): TunnelRegistry {
  const root = parseToml(text);
  const reg = emptyRegistry();
  if (typeof root.tunnel_id === "string") reg.tunnelId = root.tunnel_id;
  if (typeof root.tunnel_name === "string") reg.tunnelName = root.tunnel_name;
  if (typeof root.domain === "string") reg.domain = root.domain;
  const rawApps = (root.apps ?? {}) as Record<string, Record<string, unknown>>;
  for (const [name, a] of Object.entries(rawApps)) {
    if (typeof a !== "object" || a === null) continue;
    const hostname = String(a.hostname ?? "");
    const service = String(a.service ?? "");
    // A corrupt/partial entry (hand-edited despite the "do not" header, or
    // written by some future bug) must never reach `renderCloudflaredConfig`
    // — an empty hostname/service would render a blank ingress rule into
    // cloudflared's config. Drop it rather than pass it through silently.
    if (!hostname || !service) continue;
    reg.apps[name] = {
      hostname,
      service,
      access: Array.isArray(a.access) ? (a.access as unknown[]).map(String) : [],
      ...(a.noAccess === true ? { noAccess: true } : {}),
      ownerRoot: String(a.ownerRoot ?? ""),
    };
  }
  return reg;
}

export function serializeRegistry(reg: TunnelRegistry): string {
  const lines: string[] = [];
  lines.push(
    "# Generated by repoos tunnel — machine-level registry of every repo's published apps on this box.",
  );
  lines.push("# Do not hand-edit; see docs/tunnel-registry.md.");
  if (reg.tunnelId) lines.push(`tunnel_id = ${tomlQuote(reg.tunnelId)}`);
  if (reg.tunnelName) lines.push(`tunnel_name = ${tomlQuote(reg.tunnelName)}`);
  if (reg.domain) lines.push(`domain = ${tomlQuote(reg.domain)}`);
  for (const name of Object.keys(reg.apps).sort()) {
    const app = reg.apps[name];
    lines.push("");
    lines.push(`[apps.${name}]`);
    lines.push(`hostname = ${tomlQuote(app.hostname)}`);
    lines.push(`service = ${tomlQuote(app.service)}`);
    lines.push(`access = [${app.access.map(tomlQuote).join(", ")}]`);
    if (app.noAccess) lines.push(`noAccess = true`);
    lines.push(`ownerRoot = ${tomlQuote(app.ownerRoot)}`);
  }
  return lines.join("\n") + "\n";
}

/** Read the machine registry. Missing file reads as an empty registry. */
export function readRegistry(path: string = registryPath()): TunnelRegistry {
  const text = existsSync(path) ? readFileSync(path, "utf8") : "";
  return parseRegistry(text);
}

/**
 * Persist the machine registry (0600 — same treatment as the derived ingress
 * config). Writes to a sibling temp file and renames it over the real path
 * (atomic on POSIX) so a concurrent reader (another repo's `tunnel list`, or
 * this same read done mid-write) never observes a truncated/partial file.
 */
export function writeRegistry(reg: TunnelRegistry, path: string = registryPath()): void {
  mkdirSync(dirname(path), { recursive: true });
  const tmp = `${path}.tmp-${process.pid}-${Date.now()}`;
  writeFileSync(tmp, serializeRegistry(reg), { encoding: "utf8", mode: 0o600 });
  renameSync(tmp, path);
}

const LOCK_RETRY_MS = 25;
const LOCK_STALE_MS = 5_000;

/** Block the calling thread for `ms` without busy-spinning (a real syscall wait). */
function sleepSync(ms: number): void {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/**
 * Hold an exclusive lock on the registry while running `fn`. Two `repoos
 * tunnel` processes on the same machine — the exact scenario this registry
 * exists for — can otherwise race a read-modify-write and silently drop one
 * another's change (last write wins). A sibling `<path>.lock` file created
 * with the atomic create-if-absent (`wx`) flag serves as a simple
 * cross-process mutex: a lock older than {@link LOCK_STALE_MS} is assumed to
 * be left behind by a crashed process and is stolen rather than waited on
 * forever.
 */
export function withRegistryLock<T>(path: string, fn: () => T): T {
  const lockPath = `${path}.lock`;
  mkdirSync(dirname(path), { recursive: true });
  const start = Date.now();
  for (;;) {
    try {
      closeSync(openSync(lockPath, "wx"));
      break;
    } catch (e) {
      if ((e as NodeJS.ErrnoException).code !== "EEXIST") throw e;
      if (Date.now() - start > LOCK_STALE_MS) {
        try {
          unlinkSync(lockPath);
        } catch {
          // another waiter already stole/removed it — just retry the create
        }
        continue;
      }
      sleepSync(LOCK_RETRY_MS);
    }
  }
  try {
    return fn();
  } finally {
    try {
      unlinkSync(lockPath);
    } catch {
      // already gone (shouldn't happen — we're the holder)
    }
  }
}

/**
 * Reconcile a repo's tunnel identity against the registry's. A machine runs
 * ONE Cloudflare Tunnel, so if the registry already has an identity and this
 * repo's disagrees, refuse rather than silently picking one — returns an
 * error message. When the registry has no identity yet, adopts the repo's
 * (mutates `reg` in place). No-ops when the repo itself isn't set up yet.
 */
export function reconcileIdentity(reg: TunnelRegistry, tunnel: TunnelConfig): string | null {
  if (!tunnel.tunnelId) return null;
  if (!reg.tunnelId) {
    reg.tunnelId = tunnel.tunnelId;
    reg.tunnelName = tunnel.name;
    if (!reg.domain) reg.domain = tunnel.domain;
    return null;
  }
  if (reg.tunnelId !== tunnel.tunnelId) {
    return (
      `This repo's tunnel (${tunnel.name || "unnamed"}, ${tunnel.tunnelId}) does not match ` +
      `the machine's registered tunnel (${reg.tunnelName || "unnamed"}, ${reg.tunnelId}). ` +
      `A machine runs ONE Cloudflare Tunnel — \`repoos tunnel setup\` reuses a tunnel by NAME, ` +
      `so it won't join this one unless the names happen to match. To join it, edit this repo's ` +
      `repoos.toml [tunnel] block by hand: set tunnel_id = ${tomlQuote(reg.tunnelId)}` +
      (reg.tunnelName ? ` and name = ${tomlQuote(reg.tunnelName)}` : "") +
      `, or resolve the conflict the other way in ${registryPath()}.`
    );
  }
  return null;
}

/** Add or replace a registry entry, tagging it with its owning repo. */
export function upsertApp(
  reg: TunnelRegistry,
  name: string,
  app: TunnelApp,
  ownerRoot: string,
): void {
  reg.apps[name] = { ...app, ownerRoot };
}

/** Remove a registry entry (no-ops when absent). */
export function removeApp(reg: TunnelRegistry, name: string): void {
  delete reg.apps[name];
}

/** Strip `ownerRoot` back to plain `TunnelApp`s — the shape `renderCloudflaredConfig` expects. */
export function unionApps(reg: TunnelRegistry): Record<string, TunnelApp> {
  const out: Record<string, TunnelApp> = {};
  for (const [name, app] of Object.entries(reg.apps)) {
    out[name] = {
      hostname: app.hostname,
      service: app.service,
      access: app.access,
      ...(app.noAccess ? { noAccess: true } : {}),
    };
  }
  return out;
}

/**
 * Reconcile the registry against THIS repo's own `repoos.toml [tunnel.apps]`
 * — still the git-tracked, hand-edited source of truth for the apps this
 * repo publishes. Mutates `reg` in place and returns the names that were
 * newly seeded (for the same one-time log line callers have always printed).
 * Three cases, keyed entirely on `ownerRoot` so another repo's entries are
 * never touched:
 *
 *  - in `tunnel.apps`, missing from the registry → seed it (first run after
 *    upgrade, or a brand-new `create` on an otherwise-synced registry).
 *  - in `tunnel.apps` AND already registered under THIS repo's `ownerRoot`,
 *    but with different fields (hostname/port/access edited by hand in
 *    repoos.toml rather than through `repoos tunnel`) → overwrite the
 *    registry entry so it can't drift from the file that's supposed to be
 *    authoritative for it.
 *  - registered under THIS repo's `ownerRoot` but no longer in `tunnel.apps`
 *    (deleted by hand rather than via `repoos tunnel destroy`) → drop it,
 *    since this repo no longer declares it.
 *
 * An entry owned by a DIFFERENT repo is left alone in every case, even when
 * this repo's own `tunnel.apps` happens to declare the same name (a
 * pre-existing collision — surfaced to the user elsewhere, not silently
 * resolved here).
 *
 * Deliberately per-app rather than gated on "registry is totally empty": on
 * a machine with multiple PRE-EXISTING repos (each already publishing its
 * own apps before this registry existed), each repo seeds its own apps into
 * the registry the first time IT runs `create`/`install`/`start`, regardless
 * of whether another repo got there first and seeded its own — that's
 * exactly the scenario (celleris + dev on one tunnel) this registry exists
 * to fix. For the common single-repo case this still behaves like a
 * one-time full migration, since every app is missing on the first run and
 * every run after that is a no-op unless repoos.toml itself changed.
 */
export function syncFromRepo(reg: TunnelRegistry, tunnel: TunnelConfig, root: string): string[] {
  const seeded: string[] = [];
  for (const [name, app] of Object.entries(tunnel.apps)) {
    const existing = reg.apps[name];
    if (!existing) {
      reg.apps[name] = { ...app, ownerRoot: root };
      seeded.push(name);
      continue;
    }
    if (existing.ownerRoot !== root) continue; // another repo's entry — never touched here
    const { ownerRoot: _ownerRoot, ...current } = existing;
    if (JSON.stringify(current) !== JSON.stringify(app)) {
      reg.apps[name] = { ...app, ownerRoot: root };
    }
  }
  for (const [name, existing] of Object.entries(reg.apps)) {
    if (existing.ownerRoot === root && !tunnel.apps[name]) {
      delete reg.apps[name];
    }
  }
  return seeded;
}

/** A registry entry annotated with whether its owning repo checkout still exists on disk. */
export interface RegistryAppHealth {
  name: string;
  app: RegistryApp;
  /** `ownerRoot` no longer exists on disk — the repo that published this app is gone. */
  stale: boolean;
}

/** Every registry app, sorted by name, annotated with staleness. */
export function annotateStale(reg: TunnelRegistry): RegistryAppHealth[] {
  return Object.entries(reg.apps)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, app]) => ({
      name,
      app,
      stale: !!app.ownerRoot && !existsSync(app.ownerRoot),
    }));
}
