import type { RouteHandler } from "./types.js";
import { json, readBody } from "./utils.js";
import { createInput, enrichInput, listInputs, readInputAttachment, saveInputAttachment, updateInput, type InputStatus } from "../../core/input.js";
import { resolvePmAgent, runPrompt, recordOneShotSession } from "../agents.js";
import { getCurrentUser } from "./auth.js";

function inputPrompt(body: string): string { return ["You are the RepoOS PM agent. Classify this raw human input for triage.", "Return ONLY a JSON object with exactly these string fields:", '{"title":"short useful title","type":"idea|question|bug|improvement|feedback|other","area":"short product area or empty string"}', "Keep the title under 80 characters. Do not invent details.", "", body].join("\n"); }
function parseEnrichment(raw: string): { title?: string; type?: string; area?: string } {
  const match = raw.match(/\{[\s\S]*\}/); if (!match) return {};
  try { const value = JSON.parse(match[0]) as Record<string, unknown>; return { title: typeof value.title === "string" ? value.title : undefined, type: typeof value.type === "string" ? value.type : undefined, area: typeof value.area === "string" ? value.area : undefined }; } catch { return {}; }
}
export const getInputs: RouteHandler = (ctx, _req, res) => json(res, 200, listInputs(ctx.config));
export const postInput: RouteHandler = async (ctx, req, res) => { const b = (await readBody(req)) as Record<string, unknown>, text = typeof b.text === "string" ? b.text.trim() : ""; if (!text) return json(res, 400, { error: "text is required" }); const input = createInput(ctx.config, text, typeof b.type === "string" ? b.type : "other", getCurrentUser(req, ctx.config)?.email ?? (typeof b.createdBy === "string" ? b.createdBy : "")); const pm = resolvePmAgent(ctx.config); if (pm) { try { const result = await runPrompt(pm, inputPrompt(text), { cwd: ctx.config.root }); recordOneShotSession(ctx.config.root, pm, result, { sessionType: "pm", taskId: null }); if (result.ok && result.output) return json(res, 201, enrichInput(ctx.config, input.id, parseEnrichment(result.output))); } catch { /* raw input remains safe if enrichment fails */ } } return json(res, 201, input); };
export const patchInput: RouteHandler = async (ctx, req, res, p) => { const b = (await readBody(req)) as Record<string, unknown>; if (!["new", "reviewing", "processed"].includes(String(b.status))) return json(res, 400, { error: "invalid status" }); try { return json(res, 200, updateInput(ctx.config, p.param1, b.status as InputStatus)); } catch (e) { return json(res, 404, { error: (e as Error).message }); } };
export const uploadInputAttachment: RouteHandler = async (ctx, req, res, p) => { const b = (await readBody(req)) as Record<string, unknown>; if (typeof b.name !== "string" || typeof b.data !== "string") return json(res, 400, { error: "name and data are required" }); try { return json(res, 201, { ok: true, attachment: saveInputAttachment(ctx.config, p.param1, b.name, b.data) }); } catch (e) { return json(res, 404, { error: (e as Error).message }); } };
export const getInputAttachment: RouteHandler = (ctx, _req, res, p) => { try { const file = readInputAttachment(ctx.config, p.param1, decodeURIComponent(p.param2)); res.writeHead(200, { "Content-Type": file.mime, "Content-Length": file.data.length, "Content-Disposition": `inline; filename="${decodeURIComponent(p.param2)}"`, "Access-Control-Allow-Origin": "*" }); res.end(file.data); } catch { res.writeHead(404, { "Content-Type": "text/plain" }); res.end("Not found"); } };
