<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { X } from "lucide-vue-next";
import { useUiStore } from "../stores/ui";
import { useRepoStore } from "../stores/repo";
import Button from "../components/ui/button.vue";
import type { Input } from "../../../core/input.js";
import { relTime } from "../lib/time";
import Dialog from "../components/ui/dialog/root.vue";
import DialogClose from "../components/ui/dialog/close.vue";
import DialogContent from "../components/ui/dialog/content.vue";
import DialogDescription from "../components/ui/dialog/description.vue";
import DialogOverlay from "../components/ui/dialog/overlay.vue";
import DialogTitle from "../components/ui/dialog/title.vue";
const ui = useUiStore(), repo = useRepoStore(), inputs = ref<Input[]>([]), selected = ref(new Set(["new", "reviewing"]));
const activeInput = ref<Input | null>(null);
const statuses = [{ id: "new", label: "New", color: "#39e0ff" }, { id: "reviewing", label: "Reviewing", color: "#ffb454" }, { id: "processed", label: "Processed", color: "#4ef0a8" }];
const visible = computed(() => inputs.value.filter((i) => selected.value.has(i.status)));
async function load(): Promise<void> { inputs.value = await repo.loadInputs(); }
function toggle(id: string): void { const next = new Set(selected.value); next.has(id) ? next.delete(id) : next.add(id); selected.value = next; }
async function move(i: Input, status: string): Promise<void> { i.status = status as Input["status"]; await repo.updateInput(i.id, status); }
function openInput(input: Input): void { activeInput.value = input; }
function onInputsUpdated(): void { void load(); }
onMounted(() => { void load(); window.addEventListener("repoos:inputs-updated", onInputsUpdated); });
onBeforeUnmount(() => window.removeEventListener("repoos:inputs-updated", onInputsUpdated));
</script>
<template>
  <div class="inputs-page"><div class="inputs-header"><div><div class="page-title">Inputs</div><div class="page-desc">Ideas, questions, bugs, and feedback waiting to be shaped into work or knowledge.</div></div><Button variant="accent" class="new-btn" @click="ui.openNewInput"><span class="plus">+</span> New input</Button></div><div class="input-filters" role="group" aria-label="Filter inputs by status"><label v-for="s in statuses" :key="s.id" class="input-filter"><input type="checkbox" :checked="selected.has(s.id)" @change="toggle(s.id)" /><span class="status-dot" :style="{ background: s.color }"></span>{{ s.label }} <span class="filter-count">{{ inputs.filter(i => i.status === s.id).length }}</span></label></div><div v-if="!visible.length" class="inputs-empty"><div class="empty-title">No inputs here yet</div><div>Capture an idea, question, bug, or observation for the team.</div><Button variant="outline" @click="ui.openNewInput">Submit your first input</Button></div><div v-else class="input-list"><article v-for="i in visible" :key="i.id" class="input-row" tabindex="0" @click="openInput(i)" @keyup.enter="openInput(i)"><div class="input-row-main"><div class="input-row-meta"><span class="input-status" :class="i.status">{{ i.status }}</span><span v-if="i.type">{{ i.type }}</span><span v-if="i.area">{{ i.area }}</span><span v-if="i.createdAt">{{ new Date(i.createdAt).toLocaleDateString() }}</span></div><h2>{{ i.title }}</h2><p>{{ i.body }}</p><div v-if="i.attachments.length" class="attachment-meta">{{ i.attachments.length }} attachment{{ i.attachments.length === 1 ? '' : 's' }}</div></div><select class="status-select" :value="i.status" @click.stop @change="move(i, ($event.target as HTMLSelectElement).value)"><option v-for="s in statuses" :key="s.id" :value="s.id">{{ s.label }}</option></select></article></div>
    <Dialog :open="!!activeInput" @update:open="(v) => { if (!v) activeInput = null }"><DialogOverlay /><DialogContent :style="{ width: ui.drawerWidth + 'px', 'max-width': '100vw' }"><div class="drawer-resize" @mousedown.prevent="ui.startResize"></div><div class="drawer-head"><DialogTitle>{{ activeInput?.title }}</DialogTitle><DialogDescription class="sr-only">Input details</DialogDescription><DialogClose class="close-x"><X class="size-[15px]" /></DialogClose></div><div v-if="activeInput" class="drawer-body input-detail"><div class="detail-status"><span class="input-status" :class="activeInput.status">{{ activeInput.status }}</span></div><div class="detail-meta"><span v-if="activeInput.type">{{ activeInput.type }}</span><span v-if="activeInput.area">{{ activeInput.area }}</span><span v-if="activeInput.createdAt">Created {{ relTime(activeInput.createdAt) }}</span></div><div class="detail-body">{{ activeInput.body }}</div><div v-if="activeInput.attachments.length" class="detail-attachments"><strong>Attachments</strong><div v-for="a in activeInput.attachments" :key="a.name" class="attachment-card"><img v-if="a.mime.startsWith('image/')" :src="`/api/inputs/${activeInput.id}/attachments/${encodeURIComponent(a.name)}`" :alt="a.name" /><a :href="`/api/inputs/${activeInput.id}/attachments/${encodeURIComponent(a.name)}`" target="_blank" rel="noreferrer">{{ a.name }}</a></div></div><label class="detail-label" for="input-detail-status">Status</label><select id="input-detail-status" class="status-select detail-select" :value="activeInput.status" @change="move(activeInput, ($event.target as HTMLSelectElement).value)"><option v-for="s in statuses" :key="s.id" :value="s.id">{{ s.label }}</option></select></div></DialogContent></Dialog>
  </div>
</template>
<style scoped>
.inputs-page { max-width:1000px; margin:0 auto; padding:28px 30px 80px; }.inputs-header { display:flex; align-items:flex-end; justify-content:space-between; margin-bottom:22px; gap:20px; }.input-filters { display:flex; flex-wrap:wrap; gap:9px; padding:12px; margin-bottom:16px; background:var(--panel); border:1px solid var(--border); border-radius:11px; }.input-filter { display:inline-flex; align-items:center; gap:7px; padding:7px 10px; border-radius:8px; color:var(--txt-secondary); font-size:12px; cursor:pointer; }.input-filter:hover { background:var(--nav-hover-bg); color:var(--txt); }.input-filter input { accent-color:var(--cyan); }.status-dot { width:8px; height:8px; border-radius:50%; }.filter-count { color:var(--txt-faint); font-family:var(--font-mono); }.input-list { display:flex; flex-direction:column; gap:9px; }.input-row { display:flex; justify-content:space-between; gap:22px; padding:17px 18px; background:var(--panel); border:1px solid var(--border); border-radius:11px; cursor:pointer; }.input-row:hover, .input-row:focus-visible { border-color:var(--border-focus); outline:none; }.input-row-main { min-width:0; }.input-row h2 { margin:7px 0 5px; font-size:15px; font-weight:600; color:var(--txt); }.input-row p { margin:0; white-space:pre-wrap; color:var(--txt-secondary); font-size:13px; line-height:1.5; }.input-row-meta, .detail-meta { display:flex; gap:10px; align-items:center; color:var(--txt-faint); font-size:11px; }.input-status { padding:3px 7px; border-radius:999px; text-transform:capitalize; background:var(--bg-secondary); }.input-status.new { color:var(--cyan); }.input-status.reviewing { color:#ffb454; }.input-status.processed { color:#4ef0a8; }.status-select { align-self:flex-start; min-width:110px; padding:7px 8px; border:1px solid var(--border); border-radius:7px; background:var(--bg-secondary); color:var(--txt-secondary); font-size:12px; }.attachment-meta { margin-top:9px; color:var(--txt-faint); font-size:11px; }.inputs-empty { display:flex; flex-direction:column; align-items:center; gap:12px; padding:80px 20px; color:var(--txt-faint); text-align:center; border:1px dashed var(--border); border-radius:12px; }.empty-title { color:var(--txt); font-size:15px; font-weight:600; }.plus { font-size:18px; line-height:12px; }.input-detail { display:flex; flex-direction:column; gap:12px; }.detail-status { margin-top:-7px; }.detail-body { white-space:pre-wrap; color:var(--txt); font-size:14px; line-height:1.65; }.detail-attachments { display:flex; flex-direction:column; gap:9px; color:var(--txt-secondary); font-size:12px; }.attachment-card { display:flex; flex-direction:column; gap:5px; padding:8px; border:1px solid var(--border); border-radius:8px; }.attachment-card img { max-width:100%; max-height:260px; object-fit:contain; border-radius:5px; background:var(--bg-secondary); }.attachment-card a { color:var(--cyan); overflow-wrap:anywhere; }.detail-label { color:var(--txt-secondary); font-size:12px; }.detail-select { align-self:stretch; }
@media (max-width:650px) { .inputs-page { padding:20px 14px 70px; }.inputs-header { align-items:flex-start; flex-direction:column; }.input-row { flex-direction:column; gap:12px; }.status-select { align-self:stretch; } }
</style>
